# Generated by Django 4.2.6 on 2025-03-28 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import openstack_auth_shib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('log_type', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('project_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('dst_project_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('dst_user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('message', models.TextField()),
            ],
            managers=[
                ('objects', openstack_auth_shib.models.LogManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('projectid', models.CharField(max_length=64, null=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(db_index=True, max_length=64, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('givenname', models.CharField(max_length=255)),
                ('sn', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=64)),
                ('expdate', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMapping',
            fields=[
                ('globaluser', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('registration', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.registration')),
            ],
        ),
        migrations.CreateModel(
            name='RegRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=64, null=True)),
                ('externalid', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('flowstatus', models.IntegerField(default=0)),
                ('contactper', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.registration')),
            ],
        ),
        migrations.CreateModel(
            name='PrjRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.CharField(max_length=64)),
                ('status', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.project')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.registration')),
            ],
        ),
        migrations.CreateModel(
            name='PrjRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowstatus', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.project')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.registration')),
            ],
        ),
        migrations.CreateModel(
            name='LogExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='openstack_auth_shib.log')),
            ],
        ),
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expdate', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.project')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.registration')),
            ],
            managers=[
                ('objects', openstack_auth_shib.models.ExpManager()),
            ],
        ),
        migrations.CreateModel(
            name='EMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.registration')),
            ],
        ),
    ]
