# Generated by Django 4.2.6 on 2025-05-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstack_auth_shib', '0001_initialstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrjAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('value', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack_auth_shib.project')),
            ],
        ),
    ]
