# Generated by Django 4.2.14 on 2026-06-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack_auth_shib', '0002_prj_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='regrequest',
            name='email',
        ),
        migrations.AlterField(
            model_name='regrequest',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
